/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mt.srilm;

class srilmJNI {
  public final static native long new_unsigned_array(int jarg1);
  public final static native void delete_unsigned_array(long jarg1);
  public final static native long unsigned_array_getitem(long jarg1, int jarg2);
  public final static native void unsigned_array_setitem(long jarg1, int jarg2, long jarg3);
  public final static native long initVocab(int jarg1, int jarg2);
  public final static native long initLM(int jarg1, long jarg2);
  public final static native int readLM(long jarg1, String jarg2);
  public final static native float getProb(long jarg1, long jarg2, int jarg3, long jarg4);
  public final static native float getWordProb(long jarg1, long jarg2, long jarg3);
  public final static native long getDepth(long jarg1, long jarg2, int jarg3);
  public final static native long getIndexForWord(long jarg1, String jarg2);
  public final static native int getVocab_None();
}
