#!/usr/bin/env python
#
# Make a sequence of pause distributions from an actionlist file
# generated by actionlog_to_csv.py
#
import sys
import re
import codecs
import os
import csv
from os.path import basename
from collections import defaultdict,namedtuple
from csv_unicode import UnicodeReader,UnicodeWriter
from argparse import ArgumentParser

# Action log event
from actionlog_to_csv import Event

# Pause
Row = namedtuple('Row', 'sourceid userid duration event_before event_after')

def make_pause_file(actionlog, output_dir):
    """ Generates a pause duration file from an action log

    Args:
    Returns:
    Raises:
    """
    with open('%s/actionlog.pause.csv' % (output_dir), 'w') as out_file:
        out_csv = UnicodeWriter(out_file, quoting=csv.QUOTE_ALL)
        write_headers = True
        with open(actionlog) as in_file:
            in_csv = UnicodeReader(out_file)
            last_event = None
            for event in map(Event._make, UnicodeReader(in_file)):
                if last_event == None or not last_event.userid == event.userid:
                    # Skip start event
                    last_event = event
                    continue
                duration = int(event.time) - int(last_event.time)
                # Should probably discard below a set typing speed
                # What is the min pause between keystrokes?
                row = Row(sourceid=event.sourceid,
                          userid=event.userid,
                          duration=str(duration),
                          event_before=last_event.event_class,
                          event_after=event.event_class)
                if write_headers:
                    out_csv.writerow(list(row._fields))
                    write_headers = False
                out_csv.writerow([x for x in row._asdict().itervalues()])
                last_event = event
                
def main():
    desc='Generate a pause duration file from an actionfile'
    parser=ArgumentParser(description=desc)
    parser.add_argument('actionlog',
                        metavar='action_log',
                        help='Action log file.')
    parser.add_argument('-o', '--output_dir',
                        dest='out_dir',
                        default=None,
                        type=str,
                        help='Output directory for files.')
    args = parser.parse_args()

    output_dir = args.out_dir if args.out_dir else './'
    make_pause_file(args.actionlog, output_dir)

if __name__ == '__main__':
    main()
