#!/bin/bash

make $* \
 LANG=ae \
 LMID=bbn \
 FID=1233 \
 LMSRC="bbn-0.counts.gz  bbn-1.counts.gz  bbn-2.counts.gz  bbn-3.counts.gz  bbn-4.counts.gz  bbn-5.counts.gz" \
 LMFILTER="-gt2min 1 -gt3min 2 -gt4min 3 -gt5min 3"
