#!/bin/bash

make $* \
 LANG=ae-class \
 LMID=bbn2 \
 FID=1233 \
 LMSRC="bbn_google2006-0.counts.gz bbn_google2006-1.counts.gz bbn_google2006-2.counts.gz bbn_google2006-3.counts.gz" \
 LMFILTER="-gt2min 1 -gt3min 2 -gt4min 3 -gt5min 3"
