#!/bin/bash

make $* \
 LANG=ae \
 LMID=mtFB_giga4_afp_xin \
 FID=1233 \
 LMSRC="mt.counts.gz mtB.counts.gz fouo.counts.gz LDC2009T13-giga4-xin.counts.gz LDC2009T13-giga4-afp-0.counts.gz LDC2009T13-giga4-afp-1.counts.gz" \
 LMFILTER="-gt2min 1 -gt3min 2 -gt4min 3 -gt5min 3"
