/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_nlp_mt_base_KenLanguageModel */

#ifndef _Included_edu_stanford_nlp_mt_base_KenLanguageModel
#define _Included_edu_stanford_nlp_mt_base_KenLanguageModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_nlp_mt_base_KenLanguageModel
 * Method:    readKenLM
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_stanford_nlp_mt_base_KenLanguageModel_readKenLM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_stanford_nlp_mt_base_KenLanguageModel
 * Method:    scoreNGram
 * Signature: (J[I)D
 */
JNIEXPORT jdouble JNICALL Java_edu_stanford_nlp_mt_base_KenLanguageModel_scoreNGram
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     edu_stanford_nlp_mt_base_KenLanguageModel
 * Method:    relevantPrefixGram
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_stanford_nlp_mt_base_KenLanguageModel_relevantPrefixGram
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     edu_stanford_nlp_mt_base_KenLanguageModel
 * Method:    getId
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_nlp_mt_base_KenLanguageModel_getId
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     edu_stanford_nlp_mt_base_KenLanguageModel
 * Method:    getOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_nlp_mt_base_KenLanguageModel_getOrder
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
