#!/bin/sh

if [ $# -lt 2 ] 	
	then
  		echo "Usage: $0 <memory> <configuration file> [options]"
  		exit 1
fi

MEM=$1
CONF=$2
shift
shift

OPTS="-XX:+UseCompressedOops -Xmx$MEM -Xms$MEM"
BASEDIR=`dirname $0`
java $OPTS -jar $BASEDIR/../lib/berkeleyaligner.jar ++$CONF $@ 
