#!/usr/bin/env bash
#
# Align a bitext with the Berkeley Aligner
#
# Authors: Michel Galley, Spence Green
#

##########################################
# Word alignment with Berkeley aligner:
##########################################

if [ "$BERKELEY_ALIGNER" == "" ]; then
  #PACKAGE=/u/nlp/packages/berkeleyaligner2.0
  BERKELEY_ALIGNER=/u/nlp/packages/berkeleyaligner2.1
fi


if [ $# -ne 2 ]; then
	echo Usage: `basename $0` memory conf_file
	echo
	echo Berkeley aligner path: "$BERKELEY_ALIGNER"
	echo
	echo Set the BERKELEY_ALIGNER environment variable
	echo to set a different path.
 	exit -1
fi

MEM=$1
CONF=$2
shift 2

OPTS="-server -XX:+UseParallelGC -XX:+UseParallelOldGC -Xmx$MEM -Xms$MEM"

java $OPTS -jar "$BERKELEY_ALIGNER"/berkeleyaligner.jar ++$CONF $@ 

