#!/usr/bin/env bash
#
# Align a bitext with the Berkeley Aligner
#
# Authors: Michel Galley, Spence Green
#

##########################################
# Word alignment with Berkeley aligner:
##########################################

if [ "$BERKELEY_ALIGNER" == "" ]; then
  #PACKAGE=/u/nlp/packages/berkeleyaligner2.0
  BERKELEY_ALIGNER=/u/nlp/packages/berkeleyaligner2.1
fi


if [ $# -ne 2 ]; then
	echo Usage: `basename $0` memory conf_file
	echo
	echo Berkeley aligner: "$VERSION"
	echo
	echo Edit the VERSION variable in the script to switch
	echo between Berkeley 2.0 and 2.1.
 	exit -1
fi

MEM=$1
CONF=$2
shift
shift

OPTS="-server -XX:+UseCompressedOops -Xmx$MEM -Xms$MEM -XX:MaxPermSize=2g"

java $OPTS -jar "$BERKELEY_ALIGNER"/berkeleyaligner.jar ++$CONF $@ 
