#!/usr/bin/env bash
#
# Align a bitext with the Berkeley Aligner
#
# Authors: Michel Galley, Spence Green
#

##########################################
# Word alignment with Berkeley aligner:
##########################################

if [ $# -lt 1 ] 	
	then
  		echo "Usage: $0 <memory> <configuration file>"
  		exit 1
fi

MEM=$1
CONF=$2
shift
shift

#VERSION=/u/nlp/packages/berkeleyaligner2.0
VERSION=/u/nlp/packages/berkeleyaligner2.1

OPTS="-XX:+UseCompressedOops -Xmx$MEM -Xms$MEM -XX:MaxPermSize=2g"

java $OPTS -jar "$VERSION"/berkeleyaligner.jar ++$CONF $@ 
