#!/bin/bash

#####################################################
## Applies plain-text postprocessing to nbest list
## (1st argument is a script reading decoder output
## from stdin and writing postprocessing to stdout)
#####################################################

POST=$1
TMP=`mktemp`
sed 's/ ||| /\t/g' > $TMP
cut -f 1 $TMP > $TMP.1
cut -f 2 $TMP > $TMP.2
cut -f 3 $TMP > $TMP.3

cat $TMP.2 | $POST | en_detokenizer | nist_tok | lc > $TMP.2b
mergecols $TMP.{1,2b,3} | sed 's/\t/ ||| /g'

rm $TMP.{1,2,3,2b}
