#!/usr/bin/perl

#binmode(STDIN,":utf8");
#binmode(STDOUT,":utf8");
#binmode(STDERR,":utf8");

while(<STDIN>) {
	#s/(\s+ال){1,} / uh /g;
	s/(\s+ال){2,} / , uh , /g;
	s/(\s+b){2,}/ b/g;
	#s/(\s+ب){2,}/ ب/g;
	print;
}
