#!/usr/bin/perl
BEGIN { push @INC, "/u/mgalley/programming/perl-src/"; }

use strict;
use POSIX;
use Fatal qw(open close);
use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

use utils::opt  qw(&get_args &get_opts);
use utils::data  qw(&load_file);
use utils::mt  qw(&load_mt_sgml &load_ibm_doc_scores &load_ptable);
use utils::exec qw(&print_exec &get_exec &get_files_in_dir &sys &sysout);

die "Usage: $0 (test sgml) (dev sgml)\n" unless $#ARGV == 1;

my $testfile = $ARGV[0];
my $devfile = $ARGV[1];

my ($tseq, $test, $tdocs) = load_mt_sgml($testfile);
my ($dseq, $dev,  $ddocs) = load_mt_sgml($devfile);

my ($total,$diff) = (0,0);
for my $doc (keys %{$test}) {
	for my $id (keys %{$test->{$doc}}) {
		if(defined $dev->{$doc}{$id}) {
			my $t = $tseq->[$test->{$doc}{$id}][2];
			my $tstr = join(' ', @$t);
			my $d = $dseq->[$dev->{$doc}{$id}][2];
			my $dstr = join(' ', @$d);
			if($tstr ne $dstr) {
				print "WARNING: different:\n";
				print "test: $tstr\n";
				print "dev:  $dstr\n";
				$diff++;
			}
			$total++;
		} else {
			print STDERR "Not in dev: $doc:$id\n";
		}
	}
}
print "Diff $diff/$total\n";
