#!/usr/bin/perl
#
# Load local Phrasal Perl modules from the scripts directory.
#
use Cwd 'abs_path';
use File::Basename;
BEGIN { push @INC, dirname(abs_path($0)) }

#####################################################
# Compare two sgml files, and print segments
# that appear in both if translations are different.
#####################################################

use strict;
use Fatal qw(open close);
use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

use mt_utils qw(&load_mt_sgml &load_ibm_doc_scores &load_ptable);

die "Usage: $0 (test sgml) (dev sgml)\n" unless $#ARGV == 1;

my $testfile = $ARGV[0];
my $devfile = $ARGV[1];

my ($tseq, $test, $tdocs) = load_mt_sgml($testfile);
my ($dseq, $dev,  $ddocs) = load_mt_sgml($devfile);

my ($total,$diff) = (0,0);
for my $doc (keys %{$test}) {
	for my $id (keys %{$test->{$doc}}) {
		if(defined $dev->{$doc}{$id}) {
			my $t = $tseq->[$test->{$doc}{$id}][2];
			my $tstr = join(' ', @$t);
			my $d = $dseq->[$dev->{$doc}{$id}][2];
			my $dstr = join(' ', @$d);
			if($tstr ne $dstr) {
				print "WARNING: different:\n";
				print "test: $tstr\n";
				print "dev:  $dstr\n";
				$diff++;
			}
			$total++;
		} else {
			print STDERR "Not in dev: $doc:$id\n";
		}
	}
}
print "Diff $diff/$total\n";
