#!/bin/bash

#######################################################################
# English truecaser
#
# Reads lowercase text from stdin, and prints cased text to stdout.
# Trained on MT data (mostly newswire + small amount of speech and web data).
#######################################################################

mixed=/scr/nlp/data/gale3/NIST09/truecaser/postprocess/fixMixCasing/MixDisambiguation.list 

crf_model=/scr/nlp/data/gale3/NIST09/truecaser/crf/noUN.ser.gz
tmp=`mktemp /tmp/tc_input.XXXXXX`

host=`hostname -s`
java="java -DSRILM=true -Djava.library.path=/scr/nlp/data/gale3/SRILM-JNI/$host"

cat > $tmp

# CRF truecaser:
$java -mx5g edu.stanford.nlp.ie.crf.CRFBiasedClassifier -loadClassifier $crf_model -testFile $tmp \
	-mixedCaseMapFile $mixed -classBias INIT_UPPER:-0.7,UPPER:-0.7,O:0 \
  -readerAndWriter edu.stanford.nlp.sequences.TrueCasingForNIST09DocumentReaderAndWriter

rm -f $tmp
