#!/bin/bash

#######################################################################
# English truecaser
#
# Reads lowercase text from stdin, and prints cased text to stdout.
# Trained on Gigaword.
#######################################################################

crf_model=/scr/nlp/data/gale3/NIST09/truecaser/crf/noUN.ser.gz
lm=/scr/nlp/data/gale3/NIST09/truecaser/lm/releases/mt_giga3_afp_xin.1233.unk.lm.gz

host=`hostname -s`
java="java -DSRILM=true -Djava.library.path=/scr/nlp/data/gale3/SRILM-JNI/$host"

# LM truecaser:
cat | $java -Xmx2g mt.tools.LanguageModelTrueCaser $lm
