#!/bin/sh

BASEDIR=`dirname $0`
CP_OPTS="-cp $BASEDIR/../phrasal.jar:$BASEDIR/../lib/fastutil.jar:$BASEDIR/../lib/mtj.jar"

if [ "$1" == "-help" ]; then
			java $CP_OPTS $JAVA_OPTS edu.stanford.nlp.mt.train.PhraseExtract -help true
  		exit 1
fi

if [ $# -lt 2 ]; then
  		echo "Usage: $0 <memory> <model-directory> [options]"
  		exit 1
fi

MEM=$1
DIR=$2
shift
shift

JAVA_OPTS="-XX:+UseCompressedOops -Xmx$MEM -Xms$MEM"
EXTRACT_OPTS="-inputDir $DIR -outputFile $DIR/phrases.gz"

# Generate phrase table:
java $CP_OPTS $JAVA_OPTS edu.stanford.nlp.mt.train.PhraseExtract $EXTRACT_OPTS $@ 2> $DIR/phrases.log

# Split model into two: translation and reordering models:
zcat $DIR/phrases.gz | $BASEDIR/../scripts/split-table $DIR/phrases-tm.gz $DIR/phrases-om.gz
