#!/bin/bash

BASEDIR=`dirname $0`

if [ "$1" == "-help" ]; then
			java $JAVA_OPTS edu.stanford.nlp.mt.train.PhraseExtract -help true
  		exit 1
fi

if [ $# -lt 2 ]; then
  		echo "Usage: $0 <memory> <model-directory> [options]"
  		exit 1
fi

MEM=$1
INPATH=$2
if [ $# -ge 2 ]; then
OUTDIR=$3
shift
else
OUTDIR=$2
fi

shift
shift

JAVA_OPTS="-XX:+UseCompressedOops -Xmx$MEM -Xms$MEM"
if [ -d $INPATH ]; then
  EXTRACT_OPTS="-inputDir $INPATH -outputFile $OUTDIR/phrases.gz"
else 
  EXTRACT_OPTS="-tripleFile $INPATH -outputFile $OUTDIR/phrases.gz"
fi

# Generate phrase table:
java $JAVA_OPTS edu.stanford.nlp.mt.train.PhraseExtract $EXTRACT_OPTS $@ 2> $OUTDIR/phrases.log

# Split model into two: translation and reordering models:
zcat $OUTDIR/phrases.gz | $BASEDIR/../scripts/split-table $OUTDIR/phrases-tm.gz $OUTDIR/phrases-om.gz
