#!/bin/bash

#################################################################
# Filter ARPA LM for a given phrase table and input document.
# Any n-gram that contains a word that appears neither in 
# the target side of the phrase table nor the input document 
# is deleted.
# 
# Notes: 
# * This script requires the foreign input because it may
#   contain tokens (e.g., numbers) that appear in the LM but not
#   in the phrase table.
# * projects/mt/scripts/filter_lm does more comprehensive filter
#   (ngram-based instead of unigram-based), though this version
#   is much faster
#
# Sample usage: filter_lm_fast giga3.lm.gz phrase-table.gz mt06.ar | gzip > out.gz
# 
# Author: Michel Galley (mgalley@stanford.edu)
#################################################################

usage() {
  echo "Usage: $0 lm ptable input" >&2
  echo "  lm: SRILM ARPA backoff language model file" >&2
  echo "  ptable: gzipped Moses phrase table" >&2
  echo "  input: foreign input" >&2
	echo "The filtered LM is written to stdout." >&2
  exit
}

if [ $# != 3 ]; then
	usage
fi

lm=$1
ptable=$2
input=$3
voc=`mktemp /tmp/lm_vocab.XXXXXX`


# Extract text to create vocab:
zcat $ptable | sed 's/ ||| /\t/g' | cut -f 2 | cat - $input | \
# Create vocab:
ngram-count -text - -write-vocab - -order 1 -tolower | tee $voc | \
# Filter LM against vocab:
ngram -vocab - -lm $lm -write-lm - -order 5 -limit-vocab

echo Done. Vocabulary file stored in: $voc >&2
