#!/bin/bash

#################################################################
# Filter ARPA LM for a given phrase table and input document.
# Any n-gram that contains a word that appears neither in 
# the target side of the phrase table nor the input document 
# is deleted.
# 
# Notes: 
# * projects/mt/scripts/filter_lm does more comprehensive filter
#   (ngram-based instead of unigram-based), though this version
#   is much faster
#
# Sample usage: 
# zcat phrase-table.gz | sed 's/ ||| /\t/g' | cut -f 2 | \
# filter_lm_unigram giga3.lm.gz | gzip > out.gz
# 
# Author: Michel Galley (mgalley@stanford.edu)
#################################################################

usage() {
  echo "Usage: $0 lm" >&2
  echo "  lm: SRILM ARPA backoff language model file" >&2
	echo "." >&2
	echo "The filtered LM is written to stdout." >&2
  exit
}

if [ $# != 3 ]; then
	usage
fi

lm=$1

# Filter LM against vocab:
ngram -vocab - -lm $lm -write-lm - -order 5 -limit-vocab
