#!/bin/bash


###############################################
# IBM English tokenizer for A-E
# Author: Michel Galley
###############################################

usage() {
  echo "Usage: $0 [class]" >&2
	echo "class: IBM classing" >&2
  exit
}

if [ $# -gt 1 ]; then
	usage
fi

R=/scr/nlp/data/gale/IBMArabicScripts
if [ $# -eq 1 ]; then
	$R/delete-ext-ascii.pl | $R/classquotes.pl | $R/eng_tokenizer.pl | $R/eng_simpl_class.pl 1 0
else 
	$R/delete-ext-ascii.pl | $R/classquotes.pl | $R/eng_tokenizer.pl | perl -pe 's/^\s+//; s/\s+$/\n/'
fi

