#!/bin/bash

###############################################
# IBM Arabic tokenizer for A-E
# Author: Michel Galley
###############################################

usage() {
  echo "Usage: $0 [class]" >&2
	echo "class: IBM classing" >&2
  exit
}

if [ $# -gt 1 ]; then
	usage
fi

R=/scr/nlp/data/gale/IBMArabicScripts
if [ $# -eq 1 ]; then
	$R/ar_normalize_v5.pl | $R/ar_tokenize_v2.pl | $R/canonicalize-months.pl | $R/eng_simpl_class.pl 1 0
else 
	$R/ar_normalize_v5.pl | $R/ar_tokenize_v2.pl | $R/canonicalize-months.pl 
fi

