#!/usr/bin/perl

#####################################################
# Make an SRILM alias file that matches to each 
# mixed-case word to its lowercase equivalent.
#
# Author: Michel Galley (mgalley@stanford.edu)
#####################################################

use strict;
use POSIX;
use Fatal qw(open close);
use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

print <<'EOF';
<S> <s>
</S> </s>
<UNK> <unk>
EOF

while(<STDIN>) {
	chomp;
	if(/^[a-zA-Z]*$/) {
		tr/a-z/A-Z/;
		my $upper = $_;
		tr/A-Z/a-z/;
		my $lower = $_;
		s/^(\w)/uc($1)/e;
		my $mixed = $_;
		print $upper," ",$lower,"\n";	
		print $mixed," ",$lower,"\n";	
	} elsif(/[A-Z]/) {
		print $_," ";
		tr/A-Z/a-z/;
		print $_,"\n";	
	}
}
