#!/usr/bin/perl

my $id = $ARGV[0];

while(<STDIN>) {
	chomp;
	my @els = split(/ \|\|\| /);
	my %f = split(/\s+/, $els[2]);
	my $n = -$f{"WordPenalty:"};
	$f{$id} /= $n;
	$els[2] = join(' ', map { "$_ $f{$_}" } keys %f);
	print join(' ||| ', @els), "\n";
}
