#!/usr/bin/env python

# phrase-viewer
#
# author:  Spence Green
##############################

import sys
from optparse import OptionParser
import os
import subprocess

JAVANLP_HOME=os.environ.get('JAVANLP_HOME')
DEF_SCHEMA=JAVANLP_HOME + '/projects/mt/schema/phrase-viewer-paths.xsd'

def run_phrase_viewer(opts):
    cmd_line = 'java -Xmx%s -Xms%s mt.visualize.phrase.PhraseViewer' % (opts.jmem,opts.jmem)

    if opts.verbose:
        cmd_line = cmd_line + ' -v'
    
    cmd_line = cmd_line + ' -x ' + opts.schema
    
    if opts.pvopts:
        cmd_line = cmd_line + ' ' + opts.pvopts
    
    p = call_command(cmd_line)
    p.wait()

def call_command(command):
    process = subprocess.Popen(command.split(' '))
    return process

def main():
    global DEF_SCHEMA
    usage = 'usage: %prog [opts]'
    parser = OptionParser(usage=usage)
    parser.add_option('-m','--java-mem',dest='jmem',default='250m',help='Set JVM memory heap size (e.g. 250m)')
    parser.add_option('-v','--verbose',dest='verbose',action='store_true',default=False,help='Verbose mode')
    parser.add_option('-x','--schema',dest='schema',default=DEF_SCHEMA,help='Set schema location')
    parser.add_option('-o','--options',dest='pvopts',help='Pass options directly to Phrase Viewer')
    
    (opts,args) = parser.parse_args()
    
    if len(args) != 0:
        parser.print_help()
        sys.exit(-1)
    
    run_phrase_viewer(opts)
    
if __name__ == '__main__':
    main()
