#!/usr/bin/perl

my %sents;

my $mThreaded = 1;
while(<STDIN>) {
	if($mThreaded && /^(\d+):(.*)/) {
		$sents{$1} = $2
	} else {
		$mThreaded=0;
		print;
	}
}

for(my $i=0;;++$i) {
	last if(!defined $sents{$i});
	print "$sents{$i}\n";
}

#print STDERR "IN: $i\n"
