#!/usr/bin/perl -w

###################################################
# Script to post-process C->E MT output.
# Remove all tokens that contain 1 or more Chinese
# characters. Note this is run as a safeguard, 
# and unknown word deletion should really happen
# before or during decoding.
#
# Author: Michel Galley (mgalley@stanford.edu)
###################################################

use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

while(<STDIN>) {
	chomp;
	my @w = split /\s+/;
	my @w2;
	foreach my $w (@w) {
		if($w =~/[^\$\[\]A-Za-z0-9,.()'"%&;:+-\?\!\{\}_\*\@]/) {
			print STDERR $w,"\n";
		} else {
			push @w2, $w;
		}
	}
	print join(' ',@w2)."\n";
}
