#!/usr/bin/env bash

if [ $# -ne 3 ]; then
    echo "Usage: `basename $0` memory phrase_table file > output"
    exit -1
fi

MEM=$1
PTFILE=$2
INPUT=$3

OPTS="-server -XX:+UseParallelGC -XX:+UseParallelOldGC -Xmx$MEM -Xms$MEM"

java $OPTS edu.stanford.nlp.mt.tools.FilterOOVByPhraseTable -a $PTFILE < $INPUT

    
