#!/usr/bin/perl -n

#####################################################################
# Remove all tokens that don't look like well-formed English words.
# In particular, this script removes control characters, words 
# of different scripts (e.g., Arabic, Chinese).
#
# Author: Michel Galley
#####################################################################

use strict;
use POSIX;
use Fatal qw(open close);
use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

chomp;
my @tok;
foreach(split(/\s+/)) {
	if(/[^\$\[\]\/0-9,.()'"%&;:+-A-Za-z\#\!\?\*\_\/]/) {
		print STDERR "skip: $_\n";
		next;
	}
	push @tok, $_;
}
print join(' ',@tok),"\n";
