#!/usr/bin/perl

#####################################################
# Convert Moses nbest list into 1best list
# (keep lists in same format)
#####################################################

my $oldid = -1; 
my $maxsize = $ARGV[0];

while(<STDIN>) {
	$skip=0;
	/^(\d+)\s+/;
	$id = $1;
	if($id == $oldid) {
		$skip=1 if ++$size > $maxsize;
	} else {
		$oldid = $id;
		$size=1;
	}
	print $_ unless $skip;
}
