#!/usr/bin/perl -n

#################################################
# Tag Arabic words appearing in latin-character
# MT output (e.g., English, German, etc.) as 
# unknown, with the tags <unk> </unk>.
# This tagged text can then be used with 
# the AppTek transliterator.
#################################################

use strict;
use POSIX;
use Fatal qw(open close);
use utf8;
binmode(STDIN,":utf8");
binmode(STDOUT,":utf8");
binmode(STDERR,":utf8");

chomp;
my @els = split(/\s+/);
for my $i (0..$#els) {
	my $e = $els[$i];
	if(length($e) > 1 && $e !~ /[A-Za-z0-9\.\#\+]/) {
		$els[$i] = "<unk>$e</unk>";
	}
}

print join(' ',@els),"\n"
