#!/usr/bin/perl

################################################
# Replaces <old_id> with <new_id> within
# ttable-file, distortion-file, and lmodel-file
# Author: Michel Galley
################################################

use strict;
use POSIX;
use Fatal qw(open close);

die "Usage: $0 <old_id> <new_id>\n" unless $#ARGV == 1;
my $oldid = $ARGV[0];
my $newid = $ARGV[1];

my $field = '';
while(<STDIN>) {
	if(/^\[(\S+)\]/) {
		$field = $1;
 	}
	if($field eq 'ttable-file' ||
	   $field eq 'distortion-file' ||
	   $field eq 'lmodel-file' ||
		 $field eq 'additional-featurizers') {
		if(s/XXXX/$newid/g || s/$oldid/$newid/g) {
			if($field eq 'additional-featurizers') {
				/\((.*)\)/;
				foreach my $el (split(/,/,$1)) {
					warn "WARNING: not a file name or missing file: $el\n" if(! -f $el);
				}
			} else {
				/(\S+)$/;
				warn "WARNING: missing file: $1\n" if(! -f $1);
			}
		}
	}
	print;
}
