/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mt.syntax.decoder;

@SuppressWarnings("unchecked")
public class SWIGTYPE_p_unsigned_int {
  private long swigCPtr;

  protected SWIGTYPE_p_unsigned_int(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_unsigned_int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_unsigned_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

